name: Create a new Release
on: [push]

jobs:
  generate-dbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
            version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Generate DBs from localizations
        run: pnpm generate-dbs

  publish-release:
    runs-on: ubuntu-latest
    needs: generate-dbs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set release date and tag
        id: set_release_data
        run: |
          DATE=$(date +"%d.%m.%Y, %H:%M")
          TAG=$(date +"%d.%m.%Y-%H.%M")
          echo "release_name=Update $DATE" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Upload all the files and publish the release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_release_data.outputs.tag_name }}
          name: ${{ steps.set_release_data.outputs.release_name }}
          files: |
            dist/*.db
